fail_on_violations: true
jshint:
  enabled: false
eslint:
  enabled: true
  config_file: assets/js/.eslintrc.json
python:
  enabled: true
  config_file: tools/.flake8.ini
sass-lint:
  enabled: true
  config_file: assets/css/.sass-lint.yml
