export const variantSeperator = '_';

export const languages: Readonly<Record<string, string>> = {
  af: 'Afrikaans',
  id: 'Bahasa Indonesia',
  cy: 'Cymraeg',
  de: 'Deutsch',
  en: 'English',
  ga: 'Gaeilge',
  gv: 'Gaelg',
  gd: 'Gàidhlig',
  rn: 'Ikirundi',
  sw: 'Kiswahili',
  lg: 'Luganda',
  mt: 'Malti',
  nl: 'Nederlands',
  sq: 'Shqip',
  vi: 'Tiếng Việt',
  tr: 'Türkçe',
  az: 'azərbaycan',
  br: 'brezhoneg',
  ca: 'català',
  da: 'dansk',
  se: 'davvisámegiella',
  et: 'eesti',
  es: 'español',
  eo: 'esperanto',
  eu: 'euskara',
  fr: 'français',
  fo: 'føroyskt',
  ia: 'interlingua',
  xh: 'isiXhosa',
  zu: 'isiZulu',
  it: 'italiano',
  mfe: 'kreol morisien',
  lv: 'latviešu',
  lt: 'lietuvių',
  hu: 'magyar',
  nb: 'norsk bokmål',
  nn: 'nynorsk',
  uz: 'oʻzbekcha',
  pl: 'polski',
  pt: 'português',
  ro: 'română',
  rm: 'rumantsch',
  sk: 'slovenčina',
  sl: 'slovenščina',
  fi: 'suomi',
  sv: 'svenska',
  is: 'íslenska',
  cs: 'čeština',
  el: 'Ελληνικά',
  tg: 'Тоҷикӣ',
  ba: 'башҡортса',
  be: 'беларуская',
  bg: 'български',
  os: 'ирон',
  kum: 'къумукъча',
  ky: 'кыргызча',
  mk: 'македонски',
  ru: 'русский',
  tt: 'татарча',
  uk: 'українська',
  kk: 'қазақша',
  hy: 'հայերեն',
  he: 'עברית',
  ur: 'اردو',
  ar: 'العربية',
  fa: 'فارسی',
  ne: 'नेपाली',
  mr: 'मराठी',
  hi: 'हिंदी',
  as: 'অসমীয়া',
  bn: 'বাংলা',
  pa: 'ਪੰਜਾਬੀ',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  si: 'සිංහල',
  th: 'ไทย',
  lo: 'ລາວ',
  zh: '中文',
  ko: '한국어',
  mrj: 'Мары йӹлмӹ',
  gl: 'galego',
  myv: 'Эрзянь кель',
  oc: 'occitan',
  cv: 'чӑвашла',
  arg: 'aragonés',
  ast: 'asturianu',
  msa: 'bahasa malay',
  hbs: 'srpskohrvatski',
  srp: 'српски',
  hrv: 'hrvatski',
  bos: 'bosanski',
  nog: 'ногъайша',
  sah: 'сахалыы',
  uig: 'ئۇيغۇرچە',
  tyv: 'тыва дылда',
};

const iso639Codes: Readonly<Record<string, string>> = {
  abk: 'ab',
  aar: 'aa',
  afr: 'af',
  aka: 'ak',
  sqi: 'sq',
  amh: 'am',
  ara: 'ar',
  arg: 'an',
  hye: 'hy',
  asm: 'as',
  ava: 'av',
  ave: 'ae',
  aym: 'ay',
  aze: 'az',
  bam: 'bm',
  bak: 'ba',
  eus: 'eu',
  bel: 'be',
  ben: 'bn',
  bih: 'bh',
  bis: 'bi',
  bos: 'bs',
  bre: 'br',
  bul: 'bg',
  mya: 'my',
  cat: 'ca',
  cha: 'ch',
  che: 'ce',
  nya: 'ny',
  zho: 'zh',
  chv: 'cv',
  cor: 'kw',
  cos: 'co',
  cre: 'cr',
  hrv: 'hr',
  ces: 'cs',
  dan: 'da',
  div: 'dv',
  nld: 'nl',
  dzo: 'dz',
  eng: 'en',
  epo: 'eo',
  est: 'et',
  ewe: 'ee',
  fao: 'fo',
  fij: 'fj',
  fin: 'fi',
  fra: 'fr',
  ful: 'ff',
  glg: 'gl',
  kat: 'ka',
  deu: 'de',
  ell: 'el',
  grn: 'gn',
  guj: 'gu',
  hat: 'ht',
  hau: 'ha',
  heb: 'he',
  her: 'hz',
  hin: 'hi',
  hmo: 'ho',
  hun: 'hu',
  ina: 'ia',
  ind: 'id',
  ile: 'ie',
  gle: 'ga',
  ibo: 'ig',
  ipk: 'ik',
  ido: 'io',
  isl: 'is',
  ita: 'it',
  iku: 'iu',
  jpn: 'ja',
  jav: 'jv',
  kal: 'kl',
  kan: 'kn',
  kau: 'kr',
  kas: 'ks',
  kaz: 'kk',
  khm: 'km',
  kik: 'ki',
  kin: 'rw',
  kir: 'ky',
  kom: 'kv',
  kon: 'kg',
  kor: 'ko',
  kur: 'ku',
  kua: 'kj',
  lat: 'la',
  ltz: 'lb',
  lug: 'lg',
  lim: 'li',
  lin: 'ln',
  lao: 'lo',
  lit: 'lt',
  lub: 'lu',
  lav: 'lv',
  glv: 'gv',
  mkd: 'mk',
  mlg: 'mg',
  msa: 'ms',
  mal: 'ml',
  mlt: 'mt',
  mri: 'mi',
  mar: 'mr',
  mah: 'mh',
  mon: 'mn',
  nau: 'na',
  nav: 'nv',
  nob: 'nb',
  nde: 'nd',
  nep: 'ne',
  ndo: 'ng',
  nno: 'nn',
  nor: 'no',
  iii: 'ii',
  nbl: 'nr',
  oci: 'oc',
  oji: 'oj',
  chu: 'cu',
  orm: 'om',
  ori: 'or',
  oss: 'os',
  pan: 'pa',
  pli: 'pi',
  fas: 'fa',
  pol: 'pl',
  pus: 'ps',
  por: 'pt',
  que: 'qu',
  roh: 'rm',
  run: 'rn',
  ron: 'ro',
  rus: 'ru',
  san: 'sa',
  srd: 'sc',
  snd: 'sd',
  sme: 'se',
  smo: 'sm',
  sag: 'sg',
  srp: 'sr',
  gla: 'gd',
  sna: 'sn',
  sin: 'si',
  slk: 'sk',
  slv: 'sl',
  som: 'so',
  sot: 'st',
  azb: 'az',
  spa: 'es',
  sun: 'su',
  swa: 'sw',
  ssw: 'ss',
  swe: 'sv',
  tam: 'ta',
  tel: 'te',
  tgk: 'tg',
  tha: 'th',
  tir: 'ti',
  bod: 'bo',
  tuk: 'tk',
  tgl: 'tl',
  tsn: 'tn',
  ton: 'to',
  tur: 'tr',
  tso: 'ts',
  tat: 'tt',
  twi: 'tw',
  tah: 'ty',
  uig: 'ug',
  ukr: 'uk',
  urd: 'ur',
  uzb: 'uz',
  ven: 've',
  vie: 'vi',
  vol: 'vo',
  wln: 'wa',
  cym: 'cy',
  wol: 'wo',
  fry: 'fy',
  xho: 'xh',
  yid: 'yi',
  yor: 'yo',
  zha: 'za',
  zul: 'zu',
  hbs: 'sh',
  pes: 'fa',
};

const rtlLanguages = new Set(['heb', 'ara', 'pes', 'urd', 'uig']);

const iso639CodesInverse: Record<string, string> = {};
Object.entries(iso639Codes).forEach(([alpha3, alpha2]) => (iso639CodesInverse[alpha2] = alpha3));

export function toAlpha2Code(code: string): string;
export function toAlpha2Code(code: string | null): string | null;
export function toAlpha2Code(code: string | null): string | null {
  if (!code) {
    return code;
  }

  const splitCode = code.split(variantSeperator, 2);
  const parentCode = splitCode[0];
  const variant = splitCode[1] ? `${variantSeperator}${splitCode[1]}` : '';

  if (parentCode in iso639CodesInverse) {
    return `${parentCode}${variant}`;
  }

  if (parentCode in iso639Codes) {
    return `${iso639Codes[parentCode]}${variant}`;
  }

  return null;
}

export function toAlpha3Code(code: string): string;
export function toAlpha3Code(code: string | null): string | null;
export function toAlpha3Code(code: string | null): string | null {
  if (!code) {
    return code;
  }

  const splitCode = code.split(variantSeperator, 2);
  const parentCode = splitCode[0];
  const variant = splitCode[1] ? `${variantSeperator}${splitCode[1]}` : '';

  if (parentCode in iso639Codes) {
    return `${parentCode}${variant}`;
  }

  if (parentCode in iso639CodesInverse) {
    return `${iso639CodesInverse[parentCode]}${variant}`;
  }

  return null;
}

export const langDirection = (code: string): string => {
  return rtlLanguages.has(code) ? 'rtl' : 'ltr';
};

export const parentLang = (code: string): string => code.split(variantSeperator, 2)[0];

export const isVariant = (code: string): boolean => code.includes(variantSeperator);
