files:
  ignore: assets/css/bootstrap.css
  include: 'assets/css/**/*.css'
rules:
  no-ids: 0
  single-line-per-selector: 0
  no-color-literals: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  no-vendor-prefixes: 0
  no-css-comments: 0
  no-transition-all: 0
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  class-name-format:
    - 1
    - convention: camelcase
