name: Build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.7.0'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build --prod
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
