name: Build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build --prod
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
