name: Check
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        run: yarn tsc
      - name: Lint scripts
        run: yarn eslint
      - name: Lint styles
        run: yarn stylelint
      - name: Prettier
        run: yarn prettier
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Collect test coverage
        run: yarn coverage --ci
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      - name: Check strings
        run: make -C src/strings test
